name: GeneraDataSet

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:         # permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar Chrome y Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromedriver

      - name: Ejecutar script
        run: python TeQuieroCityBike.py

      - name: Commit & Push resultados
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update dataset snapshot"

    

       
      
      
