name: GeneraDataSet

on:
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
   build:
     runs-on: ubuntu-latest


     permissions:
       contents: write

     steps:
        - name: Checkout mi DataSet
          uses: actions/checkout@v5

        - name: Setup Python
          uses: actions/setup-python@v6
          with:
            python-version: '3.10' 

        - name: Instalar dependencias
          run: |
            pip install selenium
            pip install -r requirements.txt || true
            
        - name: Instalar Chrome y Chromedriver
          run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser chromium-chromedriver
            which chromedriver
          
        - name: Corre mi codigo
          run: python ./TeQuieroCityBike.py
            
        - name: Commit and Push changes
          uses: stefanzweifel/git-auto-commit-action@v6
          with:
            commit_message: Carga de datos
            commit_user_name: Dilan [ Github Actions ]
       
    

       
      
      
