name: CityBike Scraper 1

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write   # 👈 necesario para que github-actions[bot] pueda hacer push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Commit & Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Nuevo snapshot CityBike"
          github_token: ${{ secrets.PAT_TOKEN }}
          
      - name: Run scraper
        run: python TeQuieroCityBike.py

      - name: Commit & Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Nuevo snapshot CityBike"
