name: CityBike Scraper 1

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write   # necesario para que el bot pueda hacer push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python TeQuieroCityBike.py

      # 🔧 Aquí se corrige el problema de non-fast-forward
      - name: Pull with rebase
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase origin main

      - name: Commit & Push data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Nuevo snapshot CityBike"
