name: CityBike Scraper

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write   # necesario para push desde el bot

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python TeQuieroCityBike.py

      # 🔧 Aquí integramos primero los cambios remotos
      - name: Pull with rebase
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase origin main

      # ✅ Luego comiteamos solo si hay cambios
      - name: Commit changes
        run: |
          git add .
          git commit -m "Nuevo snapshot CityBike" || echo "No changes to commit"

      # 🚀 Finalmente hacemos el push limpio
      - name: Push changes
        run: git push origin main

