name: GeneraDataSet1

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos
  workflow_dispatch:          # ejecución manual también
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python TeQuieroCityBike.py

      - name: Commit y Push cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Nuevo snapshot CityBike"
